name: Mult-Job

on: push

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and Read files
              run: |
                    echo "God is Always Great!"
                    ls -ltr
            - name: Executing Cowsay Script
              run: |
                    chmod +x ascii-script.sh
                    ./ascii-script.sh
                    
            - name: upload a Dragon text files
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    Test:
        needs: Build
        runs-on: ubuntu-latest
        steps:
          
          - name: download a Dragon text files
            uses: actions/download-artifact@v4
            with:
              name: dragon-text-file
          - name: Test File Exists
            run: grep -i "dragon" dragon.txt
              
                
    Deploy:
        needs: [Build, Test]
        runs-on: ubuntu-latest
        steps: 

          - name: download a Dragon text files
            uses: actions/download-artifact@v4
            with:
              name: dragon-text-file
          - name: Read File
            run: cat dragon.txt

