name: my-first-workflow-multiline-with-thirdpartylibrary

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and Read files
              run: |
                    echo "God is Always Great!"
                    ls -ltr
            - name: Install cowsay
              run: ./ascii-script.sh
            
            
            
