name: Exploring Variables and Secrets

on: 
  push

env:
  IMAGENAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      
      run: echo docker build -t ${{secrets.CONTAINER_REGISTRY}}/${{variables.DOCKER_USERNAME}}/$IMAGENAME:latest 

    - name: Docker Login
      env:
        
        DOCKER_PASSWORD: password
      run: echo docker login --username=${{variables.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
    
    - name: Docker Publish
      
      run: echo docker push docker.io /${{variables.DOCKER_USERNAME}}/$IMAGENAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      
      run: echo docker run -d -p 8080:80 ${{variables.CONTAINER_REGISTRY}}/${{variables.DOCKER_USERNAME}}/$IMAGENAME:latest
