name: Exploring Variables and Secrets

on: 
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: vengateshbabu1605
        IMAGENAME: github-actions-nginx
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

    - name: Docker Login
      env:
        DOCKER_USERNAME: vengateshbabu1605
        DOCKER_PASSWORD: Dockerbabu@123
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
    - name: Docker Publish
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: vengateshbabu1605
        IMAGENAME: github-actions-nginx
      run: docker push docker.io /$DOCKER_USERNAME/$IMAGENAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: vengateshbabu1605
        IMAGENAME: github-actions-nginx
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest
