name: Exploring Variables and Secrets

on:
  workflow_dispatch:
  #push
  

env:
  IMAGENAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build 
      run: echo docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest 

    - name: Docker Login
      env:
        
        DOCKER_PASSWORD: password
      run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
    
    - name: Docker Publish
      
      run: echo docker push {{vars.CONTAINER_REGISTRY}} /${{vars.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest

  deploy:
    needs: docker
    concurrency:
      group: production-deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      
      run: echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest
