name: Exploring Variables and Secrets

on: 
  push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: vengateshbabu1605
  IMAGENAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest 

    - name: Docker Login
      env:
        
        DOCKER_PASSWORD: Dockerbabu@123
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
    - name: Docker Publish
      
      run: echo docker push docker.io /$DOCKER_USERNAME/$IMAGENAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest
